[package]
name = "uapki"
version = "0.1.0"
edition = "2024"
description = "Rust wrapper for digital-signature verification (CMS/CAdES) on top of specinfo-ua/UAPKI, direct interface without JSON"
license = "BSD-2-Clause"
repository = "https://github.com/SunRiseGG/rust-UAPKI"

[workspace]
members = ["uapki-sys"]

[dependencies]
uapki-sys = { path = "uapki-sys", version = "0.1.0" }
